//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommereceTecvibes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Image
    {
        public int PrdImg_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Image { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
